import Footer from '@/components/footer'
import type { Metadata } from 'next'

//Toast notification
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import ThemeRegistry from '@/theme/themeRegistry/ThemeRegistry'
import { Navbar } from '@/components/navbar'

export const metadata: Metadata = {
    title: 'CEFIS Courses',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='pt-br'>
            <body style={{ margin: 0, padding: 0, boxSizing: 'border-box'}}>
                <ThemeRegistry>
                    <div style={{ display: 'flex', height: '100vh', flexDirection: 'column'}}>
                        <Navbar />
                        <main style={{ flex: 1 }}>
                            {children}
                        </main>
                        <Footer />
                    </div>
                    <ToastContainer autoClose={5000}/>
                </ThemeRegistry>
            </body>
        </html>
    )
}


