import type { Metadata } from 'next'

//Toast notification
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

import ThemeRegistry from '@/theme/themeRegistry/ThemeRegistry'
import { NextAuthSessionProvider } from '@/providers/sessionProvider'

export const metadata: Metadata = {
    title: 'CEFIS Cursos',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='pt-br'>
            <body style={{ margin: 0, padding: 0, boxSizing: 'border-box' }}>
                <NextAuthSessionProvider>
                    <ThemeRegistry>
                        {children}
                        <ToastContainer autoClose={5000} />
                    </ThemeRegistry>
                </NextAuthSessionProvider>
            </body>
        </html>
    )
}


